// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Teads",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Teads", targets: ["AATKit-Teads"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Teads",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATTeadsAdapter",
                    "AATTeadsSDK",
                    "AATOMSDK_Teads",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Teads"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATTeadsAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATTeadsAdapter.zip",
            checksum: "b9ea0aa6d7f763115a362b7eaf5e5c44da0cbbeb204db9a88200d93d448fbf90"
        ),
        .binaryTarget(
            name: "AATTeadsSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/TeadsSDK.zip",
            checksum: "5c6bc7d175fb455633c2518f5b29569ea4f6c3b69dc9bc098b10348d0b2b09fd"
        ),
        .binaryTarget(
            name: "AATOMSDK_Teads",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/OMSDK_Teads.zip",
            checksum: "2558c25f3d0eaa40f9a6d1935202c4d7b18d3d60b8eed6150be9ae9de379f0b5"
        ),
    ]
)
