// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Teads",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Teads", targets: ["AATKit-Teads"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Teads",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATTeadsAdapter",
                    "AATTeadsSDK",
                    "AATOMSDK_Teads",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Teads"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATTeadsAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATTeadsAdapter.zip",
            checksum: "2e5db373052e8cde3eb19bf08698c2ccde895cb844cdf44f4bf07e893d0df9e8"
        ),
        .binaryTarget(
            name: "AATTeadsSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/TeadsSDK.zip",
            checksum: "3af71881e8a4e39e42b9f68aeedd6c4d3b3314414d07ebc158ca996d0e48896c"
        ),
        .binaryTarget(
            name: "AATOMSDK_Teads",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/OMSDK_Teads.zip",
            checksum: "6c2e4adaede1e15365a03a7c93792f49e79e32adc54ec2d6befdf606cd950bd1"
        ),
    ]
)
