// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-Teads",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Teads", targets: ["AATKit-Teads"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta2"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-Teads",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    "AATTeadsAdapter",
                    "AATTeadsSDK",
                    "AATOMSDK_Teadstv",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-Teads"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATTeadsAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/AATTeadsAdapter.zip",
            checksum: "6976440c9d1c8a4a1a94a133199ff5f23d8a91997e21dedc467e2011be638127"
        ),
        .binaryTarget(
            name: "AATTeadsSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/TeadsSDK.zip",
            checksum: "98ded585d017267c5bfa7ff9c142c9c2889a3747165a66480456337b29229498"
        ),
        .binaryTarget(
            name: "AATOMSDK_Teadstv",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta2/OMSDK_Teadstv.zip",
            checksum: "73047c9d464779ac0967599b1df3189b5ec50d7b6612e9c5c6137bb2e555e0f1"
        ),
    ]
)
